namespace: coldfront
resources:
  - configmap.yaml
  - secrets/coldfront.yaml
  - secrets/coldfront-tls.yaml
  - secrets/pgo-s3-conf.yaml
  - secrets/pgo-pgbackrest-secrets.yaml
  - ha-postgres.yaml
  - ../../base
  - ingress.yaml
patchesStrategicMerge:
  - patches/coldfront-deployment.yaml
  - patches/qcluster-deployment.yaml
