namespace: coldfront
resources:
  - configmap.yaml
  - secrets/coldfront.yaml
  - secrets/coldfront-tls.yaml
  - ha-postgres.yaml
  - ../../base
  - ingress.yaml
patchesStrategicMerge:
  - patches/coldfront-deployment.yaml
