---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: coldfront-tls
  namespace: coldfront
spec:
  target:
    name: coldfront-tls
    template:
      type: kubernetes.io/tls
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - key: coldfront/coldfront-tls
