apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: coldfront-secrets
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: coldfront-secrets
  data:
  - secretKey: OIDC_RP_CLIENT_ID
    remoteRef:
      key: coldfront/oidc
      property: OIDC_RP_CLIENT_ID
  - secretKey: OIDC_RP_CLIENT_SECRET
    remoteRef:
      key: coldfront/oidc
      property: OIDC_RP_CLIENT_SECRET
  - secretKey: OPENSTACK_NERC_APPLICATION_CREDENTIAL_ID
    remoteRef:
      key: coldfront/nerc-openstack-app-creds
      property: OPENSTACK_NERC_APPLICATION_CREDENTIAL_ID
  - secretKey: OPENSTACK_NERC_APPLICATION_CREDENTIAL_SECRET
    remoteRef:
      key: coldfront/nerc-openstack-app-creds
      property: OPENSTACK_NERC_APPLICATION_CREDENTIAL_SECRET
  - secretKey: KEYCLOAK_USER
    remoteRef:
      key: coldfront/keycloak-creds
      property: KEYCLOAK_USER
  - secretKey: KEYCLOAK_PASS
    remoteRef:
      key: coldfront/keycloak-creds
      property: KEYCLOAK_PASS
