apiVersion: apps/v1
kind: Deployment
metadata:
  name: coldfront-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coldfront
      coldfront-deployment: coldfront-app
  template:
    metadata:
      labels:
        app: coldfront
        coldfront-deployment: coldfront-app
    spec:
      containers:
      - name: coldfront
        image: ghcr.io/nerc-project/coldfront-nerc:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: coldfront-configmap
