apiVersion: apps/v1
kind: Deployment
metadata:
  name: coldfront-qcluster-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coldfront
      coldfront-deployment: coldfront-qcluster-app
  template:
    metadata:
      labels:
        app: coldfront
        coldfront-deployment: coldfront-qcluster-app
    spec:
      containers:
        - name: coldfront-qcluster
          #image: ghcr.io/nerc-project/coldfront-nerc:main
          #imagePullPolicy: Always
          image: culbert/coldfront:latest
          imagePullPolicy: Never
          command: ["python"]
          args: ["-m", "django", "qcluster"]
          envFrom:
            - configMapRef:
                name: coldfront-configmap
